// The nostalgia series' own names and descriptions in English (content/nostalgia-series/*.md), for lib/i18n/mirror.cjs.
// A new series needs its line here; until then its Arabic name shows up in the build log's «[en] still Arabic».
module.exports = {
  "اكستريم رولز 2012": "Extreme Rules 2012",
  "باد بلود 1997": "Badd Blood 1997",
  "تي ال سي 2013": "TLC 2013",
  "كلاش اوف تشامبيونز 2019": "Clash of Champions 2019",
  "موني ان ذا بانك 2010": "Money in the Bank 2010",
  "برنامج دبليو دبليو اف تف انف الموسم الاول": "WWF Tough Enough Season 1",
  "برنامج دبليو دبليو اف تف انف الموسم الثاني": "WWF Tough Enough Season 2",
  "دبليو دبليو اف تف انف الموسم الاول": "WWF Tough Enough Season 1",
  "دبليو دبليو اف تف انف الموسم الثاني": "WWF Tough Enough Season 2",

  "رحلة البناء الكاملة لعرض اكستريم رولز 2012؛ من صدمة عودة بروك ليسنر واعتدائه على جون سينا، وصراع سي إم بانك وكريس جيريكو على بطولة العالم وغيرها من العدوات، مرتبة بالعروض الاسبوعية الكاملة مترجمة وحتى ليلة العرض الشهري.":
    "The complete road to Extreme Rules 2012: from Brock Lesnar's shock return and his attack on John Cena to CM Punk and Chris Jericho's fight over the WWE Championship, and every other rivalry, told through the full weekly shows in order, all the way to the night of the event.",
  "رحلة البناء الكاملة لعرض باد بلود 1997؛ من اشتعال الصراع التاريخي بين شون مايكلز وأندرتيكر وولادة أول قفص جحيم في التاريخ لحسم المنافس الأول، وتتويج أوين هارت بلقب القارات أمام فاروق ومواجهة كروست ذا كلوون ضد كين دوك وغيرها من العداوات، مرتبة بالعروض الأسبوعية الكاملة مترجمة وحتى ليلة العرض الشهري.":
    "The complete road to Badd Blood 1997: from the historic feud between Shawn Michaels and The Undertaker and the very first Hell in a Cell to decide the number one contender, to Owen Hart winning the Intercontinental Championship against Faarooq, and every other rivalry, told through the full weekly shows in order, all the way to the night of the event.",
  "برنامج دبليو دبليو اف تف انف (الموسم الثاني)؛ يعود برنامج البحث عن نجم المصارعة القادم بمنافسة أقوى وتحديات أكثر صعوبة، حيث يخوض مجموعة جديدة من المتسابقين تدريبات شاقة واختبارات بدنية وذهنية وتصفيات حاسمة تحت إشراف نجوم ومدربي دبليو دبليو اف، في رحلة مليئة بالمنافسة والضغط لإثبات من يستحق الوصول إلى النهاية والفوز بعقد الاحتراف، بجميع الحلقات كاملة ومترجمة حتى إعلان الفائز.":
    "WWF Tough Enough, Season 2: the search for wrestling's next star returns with tougher competition and harder challenges. A new group of contestants goes through grueling training, physical and mental tests and decisive eliminations under WWF stars and trainers, all fighting to prove who deserves to reach the end and win a pro contract. Every episode in full, up to the moment the winner is announced.",
  "برنامج دبليو دبليو اف تف انف (الموسم الأول)؛ المنافسة الحقيقية خلف الكواليس لاقتناص عقد الاحتراف في دبليو دبليو اف ، حيث يخوض المتسابقون تدريبات شاقة وتصفيات أسبوعية حاسمة تحت إشراف أساطير الحلبة، مرتبة بجميع الحلقات كاملة ومترجمة حتى إعلان الفائز بالعقد.":
    "WWF Tough Enough, Season 1: the real competition behind the curtain for a WWF contract. The contestants go through grueling training and decisive weekly eliminations under the guidance of ring legends. Every episode in full and in order, up to the moment the contract winner is announced.",
  "رحلة البناء الكاملة لعرض تي إل سي 2013؛ من إعلان صراع توحيد اللقبين التاريخي بين جون سينا وراندي أورتن لصناعة البطل الأوحد، ومواجهة سي إم بانك ودانيال براين ضد سطوة ذا شيلد وعائلة وايت وغيرها من العداوات، مرتبة بالعروض الأسبوعية الكاملة مترجمة وحتى ليلة العرض الشهري.":
    "The complete road to TLC 2013: from the announcement of John Cena vs. Randy Orton to unify the two world titles and crown one undisputed champion, to CM Punk and Daniel Bryan standing up to The Shield and The Wyatt Family, and every other rivalry, told through the full weekly shows in order, all the way to the night of the event.",
  "رحلة البناء الكاملة لعرض كلاش اوف تشامبيونز 2019؛ من صدمة ظهور \"الفيند\" براي وايت واعتدائه على سيث رولينز عقب احتفاظه ببطولة العالم الشامل أمام براون سترومان، وصراع بيكي لينش وساشا بانكس على بطولة الراو للسيدات، وعداء كوفي كينغستون وراندي أورتون على بطولة العالم، وغيرها من العداوات، مرتبة بالعروض الأسبوعية الكاملة مترجمة وحتى ليلة العرض الشهري.":
    "The complete road to Clash of Champions 2019: from the shock debut of \"The Fiend\" Bray Wyatt and his attack on Seth Rollins after Rollins kept the Universal Championship against Braun Strowman, to Becky Lynch and Sasha Banks battling over the RAW Women's Championship and Kofi Kingston's rivalry with Randy Orton over the WWE Championship, and every other rivalry, told through the full weekly shows in order, all the way to the night of the event.",
  "رحلة البناء الكاملة لأولى نسخ عرض موني إن ذا بانك المستقلة في التاريخ (Money in the Bank 2010)؛ من صراع النجوم على حقيبتي الراو وسماكداون بحثاً عن فرصة العمر، واشتعال العداوة بين جون سينا وشيمس على بطولة الـ WWE داخل القفص الحديدي ورعب عصابة النيكسوس، ونزال ري ميستيريو وجاك سواغر على بطولة العالم للوزن الثقيل، وبحث كين الغاضب عن المتسبب في إصابة الأندرتيكر، وغيرها من النزالات، مرتبة بالعروض الأسبوعية الكاملة وحتى ليلة العرض الشهري.":
    "The complete road to the first-ever Money in the Bank event (Money in the Bank 2010): from the race for the RAW and SmackDown briefcases and the chance of a lifetime, to John Cena and Sheamus fighting over the WWE Championship inside a steel cage under the threat of The Nexus, Rey Mysterio against Jack Swagger for the World Heavyweight Championship and an enraged Kane hunting for whoever injured The Undertaker, and every other match, told through the full weekly shows in order, all the way to the night of the event.",
};
